---
# Used to configure yamlling so it skips some checks
extends: default

rules:
#  line-length: disable
#  comments: disable
#  comments-indentation: disable
  document-start: disable
#  indentation: disable

ignore: |
  custom_components/
  .git
  .github/workflows/yaml-lint.yaml
  themes/
