- id: '1607949947296'
  alias: Send a camera snapshot when motion is detected
  description: ''
  use_blueprint:
    path: vorion/send-camera-snapshot-notification-on-motion.yaml
    input:
      delay: 0
      motion_sensor: binary_sensor.motion_uvc_g3_pro_front
      camera: camera.uvc_g3_pro_front
      notify_device: 6d34f062b6c1898ca60db74f88c562e6
      is_ios: true
      notification_message: '{{ motion_sensor_name }} detected movement!'
- id: '1612867372715'
  alias: Zone Notification (FF Work Nijmegen)
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.fenne
      notify_device: 6d34f062b6c1898ca60db74f88c562e6
      zone_entity: zone.work_fenne_nijmegen
- id: '1612867409866'
  alias: Zone Notification (FF Work Vught)
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.fenne
      notify_device: 6d34f062b6c1898ca60db74f88c562e6
      zone_entity: zone.work_fenne_vught
- id: '1612980102342'
  alias: Update OpenUV 5 minutes before sunrise and after sunset
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: -00:05:00
  - platform: sun
    event: sunset
    offset: 00:05:00
  condition: []
  action:
  - service: openuv.update_uv_index_data
    data: {}
  mode: single
- id: '1612980243699'
  alias: Update OpenUV every 30 minutes during daytime
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '30'
  condition:
  - condition: and
    conditions:
    - condition: sun
      before: sunset
      after: sunrise
  action:
  - service: openuv.update_uv_index_data
    data: {}
  mode: single
- id: '1612980343472'
  alias: Update OpenUV protection window daily
  description: ''
  trigger:
  - platform: time
    at: 02:12:00
  condition: []
  action:
  - service: openuv.update_protection_data
    data: {}
  mode: single
- id: '1623004018165'
  alias: Hue Dimmer Switch Study Room
  description: ''
  use_blueprint:
    path: vanstinator/zha-philips-hue-dimmer-switch-rwl020-rwl021.yaml
    input:
      remote: f2f515c72a43a7cbf44b1af01098ed6c
      brightness: 80
      light:
        area_id: 4e588329bb6b4725a635aca3260970e0
      force_brightness: false
- id: '1623004111448'
  alias: Hue Dimmer Switch Bedroom
  description: ''
  use_blueprint:
    path: vanstinator/zha-philips-hue-dimmer-switch-rwl020-rwl021.yaml
    input:
      remote: 7a95380da4b6b277a58d8d50e6563947
      light:
        area_id:
        - 236628dd9b2341f09ce0edc0f3861977
        - 4e588329bb6b4725a635aca3260970e0
        - 13328c04b1b440789f6944bd19a3def1
        - 6ed33154b4d444b0b37b012a1f13d6ed
        - b1352033ec3147e1911c9d5e60a1361c
        - 8f22318d846d409398d85596cfd5bf8c
        - c875e4db9fb44651bc804138fdbe430b
      brightness: 50
- id: '1623005346863'
  alias: Hue Dimmer Switch Downstairs
  description: ''
  use_blueprint:
    path: vanstinator/zha-philips-hue-dimmer-switch-rwl020-rwl021.yaml
    input:
      remote: be13f5952c5470501943d9363012da8d
      light:
        area_id:
        - c875e4db9fb44651bc804138fdbe430b
        - 6ed33154b4d444b0b37b012a1f13d6ed
        - b1352033ec3147e1911c9d5e60a1361c
      brightness: 50
- id: '1623006218863'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      actions:
      - service: notify.wesley_telegram
        data:
          message: '{{sensors}} battery is low. Please change the battery!'
- id: '1623006343409'
  alias: Zone Notification (FF Home)
  description: ''
  use_blueprint:
    path: Sjorsa/notify-entering-zone.yaml
    input:
      person_entity: person.fenne
      zone_entity: zone.home
      notify_device: 6d34f062b6c1898ca60db74f88c562e6
- id: '1649249933414'
  alias: Notify lowest gas price
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.gas_station_euro95_lowest_price_1
  condition: []
  action:
  - service: notify.wesley_telegram
    data:
      message: 'Euro 95 price is € {{ states.sensor.gas_station_euro95_lowest_price_1.state
        }} at {{ state_attr("sensor.gas_station_euro95_lowest_price_1","friendly_name")
        }}. '
      data:
        url: https://www.google.com/maps/search/?api=1&query={{ state_attr("sensor.gas_station_euro95_lowest_price_1","latitude")
          }},{{ state_attr("sensor.gas_station_euro95_lowest_price_1", "longitude")
          }}
  mode: single
- id: '1649250131376'
  alias: System shutdown notification
  description: ''
  trigger:
  - platform: homeassistant
    event: shutdown
  condition: []
  action:
  - service: notify.wesley_telegram
    data:
      message: Home Assistant is shutting down... Bye!
  mode: single
- id: '1649250204764'
  alias: System start notification
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: notify.wesley_telegram
    data:
      message: Home Assistant is starting up again 🎉
  mode: single
- id: '1649250405677'
  alias: Update Gas Stations
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '30'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: dgp/gas_stations
      payload_template: '{"fuel_type":"euro95","radius":5,"latitude":{{ state_attr("person.wesley",
        "latitude") }},"longitude":{{ state_attr("person.wesley", "longitude") }},
        "to_publish":5}'
  mode: single
- id: '1649255352767'
  alias: Home Assistant update notification
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.home_assistant_versions_update_available
    to: Update Available
  condition: []
  action:
  - service: notify.wesley_telegram
    data:
      message: Home Assistant update is available
  mode: single
