- id: '1612867372715'
  alias: Zone Notification (FF Work Nijmegen)
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.fenne
      notify_device: 6d34f062b6c1898ca60db74f88c562e6
      zone_entity: zone.work_fenne_nijmegen
- id: '1612867409866'
  alias: Zone Notification (FF Work Vught)
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.fenne
      notify_device: 6d34f062b6c1898ca60db74f88c562e6
      zone_entity: zone.work_fenne_vught
- id: '1612980102342'
  alias: Update OpenUV 5 minutes before sunrise and after sunset
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: -00:05:00
  - platform: sun
    event: sunset
    offset: 00:05:00
  condition: []
  action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: sensor.current_uv_index
  mode: single
- id: '1612980243699'
  alias: Update OpenUV every 30 minutes during daytime
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '30'
  condition:
  - condition: and
    conditions:
    - condition: sun
      before: sunset
      after: sunrise
  action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: sensor.current_uv_index
  mode: single
- id: '1612980343472'
  alias: Update OpenUV protection window daily
  description: ''
  trigger:
  - platform: time
    at: 02:12:00
  condition: []
  action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: binary_sensor.protection_window
  mode: single
- id: '1623006218863'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      actions:
      - service: notify.wesley_telegram
        data:
          message: '{{sensors}} battery is low. Please change the battery!'
- id: '1623006343409'
  alias: Zone Notification (FF Home)
  description: ''
  use_blueprint:
    path: homeassistant/notify_entering_zone.yaml
    input:
      person_entity: person.fenne
      zone_entity: zone.home
      notify_device: 6d34f062b6c1898ca60db74f88c562e6
- id: '1649250131376'
  alias: System shutdown notification
  description: ''
  trigger:
  - platform: homeassistant
    event: shutdown
  condition: []
  action:
  - service: notify.wesley_telegram
    data:
      message: Home Assistant is shutting down.
  mode: single
- id: '1649250204764'
  alias: System start notification
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: notify.wesley_telegram
    data:
      message: Home Assistant has started up again.
  mode: single
- id: '1649250405677'
  alias: Update Gas Stations
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '30'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: dgp/gas_stations
      payload_template: '{"fuel_type":"euro95","radius":5,"latitude":{{ state_attr("person.wesley",
        "latitude") }},"longitude":{{ state_attr("person.wesley", "longitude") }},
        "to_publish":5}'
  mode: single
- id: '1649255352767'
  alias: Home Assistant update notification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.home_assistant_versions_update_available
    - update.home_assistant_core_update
    - update.home_assistant_supervisor_update
    - update.home_assistant_operating_system_update
    to: 'on'
  condition: []
  action:
  - service: notify.wesley_telegram
    data:
      message: Home Assistant update is available!
      title: HA update available
  mode: single
- id: '1656945637447'
  alias: Home Assistant starts ➔ Update Group - Chores
  trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: call_service
    event_data:
      domain: group
      service: reload
  condition: []
  action:
  - service: group.set
    data_template:
      name: All Chores
      object_id: chores
      entities: "{% set ns = namespace(entities=[]) %}\n{% for s in states.input_button
        if s.object_id.startswith('chore_') %}\n  {% set ns.entities = ns.entities
        + [ s.entity_id ] %}\n{% endfor %}\n{{ ns.entities }}\n"
  mode: single
- id: '1658263288463'
  alias: Windows open warning
  description: Sends notification to open windows. Triggered the first time each day
    that the outside temperature is more than 0.5 degrees below indoor temperature.
  trigger:
  - platform: numeric_state
    entity_id: sensor.temperature_indoor_outdoor_difference
    for:
      hours: 0
      minutes: 10
      seconds: 0
    below: -0.5
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.evening_temperature_warning_fired
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.irosma27_temperature
        state: unavailable
    - condition: numeric_state
      entity_id: sensor.avg_temp_indoor
      above: 20
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.evening_temperature_warning_fired
    data: {}
  - service: notify.wesley_telegram
    data:
      message: It is now 0.5 degrees cooler outside than inside. Consider opening
        the windows.
      title: Cold outside!
  mode: single
- id: '1658263443149'
  alias: Reset Morning Temperature Warning
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.morning_temperature_warning_fired
  mode: single
- id: '1658263470685'
  alias: Reset Evening Temperature Warning
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.evening_temperature_warning_fired
  mode: single
- id: '1669983996137'
  alias: Smart switch bedroom
  description: ''
  use_blueprint:
    path: vandalon/z2m EnOcean PTM 215Z (Friends of Hue) switch.yaml
    input:
      controller: Smart switch bedroom
      button_3_pressed:
      - service: light.turn_on
        data:
          transition: 1
          brightness_pct: 80
        target:
          device_id: 17249d23849dd37faf257b3fe1d78ca2
      button_4_pressed:
      - service: light.turn_off
        data:
          transition: 1
        target:
          device_id: 17249d23849dd37faf257b3fe1d78ca2
      button_3_held:
      - service: light.turn_on
        data:
          transition: 1
          brightness_pct: 20
        target:
          device_id: 17249d23849dd37faf257b3fe1d78ca2
- id: '1670232852305'
  alias: Smart switch dining room
  description: ''
  use_blueprint:
    path: vandalon/z2m EnOcean PTM 215Z (Friends of Hue) switch.yaml
    input:
      controller: Smart switch dining room
      button_3_pressed:
      - service: light.turn_on
        data:
          transition: 1
          brightness_pct: 80
        target:
          device_id: 090693b1f4c84bb93c78e4fd9f12bd1f
      button_4_pressed:
      - service: light.turn_off
        data:
          transition: 1
        target:
          device_id: 090693b1f4c84bb93c78e4fd9f12bd1f
      button_3_held:
      - service: light.turn_on
        data:
          transition: 1
          brightness_pct: 20
        target:
          device_id: 090693b1f4c84bb93c78e4fd9f12bd1f
- id: '1679055487698'
  alias: Windows close warning
  description: Sends notification to open windows. Triggered the first time each day
    that the outside temperature is more than 0.5 degrees below indoor temperature.
  trigger:
  - platform: numeric_state
    entity_id: sensor.temperature_indoor_outdoor_difference
    for:
      hours: 0
      minutes: 10
      seconds: 0
    above: 0.5
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.morning_temperature_warning_fired
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.irosma27_temperature
        state: unavailable
    - condition: numeric_state
      entity_id: sensor.avg_temp_indoor
      above: 20
  action:
  - service: input_boolean.turn_on
    target:
      entity_id:
      - input_boolean.morning_temperature_warning_fired
    data: {}
  - service: notify.wesley_telegram
    data:
      message: It is now 0.5 degrees warmer outside than inside. Consider closing
        the windows!
      title: Hot outside!
  mode: single
- id: '1698659361688'
  alias: "Awtrix Spotify NowPlaying \U0001F3B9"
  description: Awtrix Spotify Now Playing
  trigger:
  - platform: state
    entity_id: media_player.spotify_weaseladhd
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: media_player.spotify_weaseladhd
        state: playing
      - condition: state
        entity_id: media_player.spotify_weaseladhd
        attribute: media_content_type
        state: music
      sequence:
      - service: mqtt.publish
        data:
          qos: 0
          retain: false
          payload: "{\n  \"text\": \"{{ state_attr('media_player.spotify_weaseladhd',
            'media_artist') }} - {{ state_attr('media_player.spotify_weaseladhd',
            'media_title') }}\",\n  \"icon\": \"18207\",\n  \"rainbow\": true,\n  \"repeat\":
            2,\n  \"pushIcon\": 0,\n  \"textCase\": 0,\n  \"textOffset\": 15,\n  \"progress\":
            {{ ( states.media_player.spotify_weaseladhd.attributes.media_position
            / states.media_player.spotify_weaseladhd.attributes.media_duration * 100
            ) | round() }},\n  \"progressC\": \"18B04C\"\n}"
          topic: awtrix_ed5c1c/custom/spotify
    - conditions:
      - condition: template
        value_template: '{{ not states.media_player.spotify_weaseladhd.state == ''playing''
          }}'
      sequence:
      - service: mqtt.publish
        data:
          qos: 0
          retain: false
          topic: awtrix_ed5c1c/custom/spotify
- id: '1699860413424'
  alias: Heating Control Living Room
  description: ''
  use_blueprint:
    path: panhans/heating_control.yaml
    input:
      heating:
      - climate.living_room
      persons:
      - person.fenne
      - person.wesley
      min_temp: 17
      guest_mode: input_boolean.guest_mode
      presence_sensor: binary_sensor.activity_in_living_room
      set_temp: input_number.comfort_temperature
      party_mode: input_boolean.party_mode
      scheduler: schedule.heating_schedule
- id: '1699860953331'
  alias: Heating Control Study
  description: ''
  use_blueprint:
    path: panhans/heating_control.yaml
    input:
      heating:
      - climate.study
      persons:
      - person.wesley
      scheduler: schedule.heating_schedule_study
      min_temp: 15
      set_temp: input_number.comfort_temperature_study
      window: binary_sensor.study_window_sensor_contact
      presence_sensor: binary_sensor.activity_in_study
- id: '1699870936576'
  alias: UniFi Protect Motion / Smart Detection Notifications
  description: ''
  use_blueprint:
    path: AngellusMortis/notification_smart_motion_event.yaml
    input:
      obj_sensor:
      - binary_sensor.uvc_g4_doorbell_motion
      presence_filter:
      - device_tracker.iphone_wv
      time_format: '%H:%M'
- id: '1699871133965'
  alias: UniFi Protect Doorbell Ring Notifications
  description: ''
  use_blueprint:
    path: AngellusMortis/notification_ring_event.yaml
    input:
      doorbell_sensor:
      - binary_sensor.uvc_g4_doorbell_doorbell
      lock_entity: lock.nuki_locky_lock
      time_format: '%H:%M'
- id: '1699871224959'
  alias: Send a camera snapshot when motion is detected
  description: ''
  use_blueprint:
    path: vorion/send-camera-snapshot-notification-on-motion.yaml
    input:
      motion_sensor: binary_sensor.uvc_g4_doorbell_motion
      camera: camera.uvc_g4_doorbell_high
      notify_device: 6d34f062b6c1898ca60db74f88c562e6
      is_ios: true
      delay: 1
