- id: '1607949947296'
  alias: Send a camera snapshot when motion is detected
  description: ''
  use_blueprint:
    path: vorion/send-camera-snapshot-notification-on-motion.yaml
    input:
      delay: 0
      motion_sensor: binary_sensor.motion_uvc_g3_pro_front
      camera: camera.uvc_g3_pro_front
      notify_device: 6d34f062b6c1898ca60db74f88c562e6
      is_ios: true
      notification_message: '{{ motion_sensor_name }} detected movement!'
- id: '1612867372715'
  alias: Zone Notification (FF Work Nijmegen)
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.fenne
      notify_device: 6d34f062b6c1898ca60db74f88c562e6
      zone_entity: zone.work_fenne_nijmegen
- id: '1612867409866'
  alias: Zone Notification (FF Work Vught)
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.fenne
      notify_device: 6d34f062b6c1898ca60db74f88c562e6
      zone_entity: zone.work_fenne_vught
- id: '1612980102342'
  alias: Update OpenUV 5 minutes before sunrise and after sunset
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: -00:05:00
  - platform: sun
    event: sunset
    offset: 00:05:00
  condition: []
  action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: sensor.current_uv_index
  mode: single
- id: '1612980243699'
  alias: Update OpenUV every 30 minutes during daytime
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '30'
  condition:
  - condition: and
    conditions:
    - condition: sun
      before: sunset
      after: sunrise
  action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: sensor.current_uv_index
  mode: single
- id: '1612980343472'
  alias: Update OpenUV protection window daily
  description: ''
  trigger:
  - platform: time
    at: 02:12:00
  condition: []
  action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: binary_sensor.protection_window
  mode: single
- id: '1623006218863'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      actions:
      - service: notify.wesley_telegram
        data:
          message: '{{sensors}} battery is low. Please change the battery!'
- id: '1623006343409'
  alias: Zone Notification (FF Home)
  description: ''
  use_blueprint:
    path: Sjorsa/notify-entering-zone.yaml
    input:
      person_entity: person.fenne
      zone_entity: zone.home
      notify_device: 6d34f062b6c1898ca60db74f88c562e6
- id: '1649249933414'
  alias: Notify lowest gas price
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.gas_station_euro95_lowest_price_1
  condition: []
  action:
  - service: notify.wesley_telegram
    data:
      message: 'Euro 95 price is € {{ states.sensor.gas_station_euro95_lowest_price_1.state
        }} at {{ state_attr("sensor.gas_station_euro95_lowest_price_1","friendly_name")
        }}. '
      data:
        url: https://www.google.com/maps/search/?api=1&query={{ state_attr("sensor.gas_station_euro95_lowest_price_1","latitude")
          }},{{ state_attr("sensor.gas_station_euro95_lowest_price_1", "longitude")
          }}
  mode: single
- id: '1649250131376'
  alias: System shutdown notification
  description: ''
  trigger:
  - platform: homeassistant
    event: shutdown
  condition: []
  action:
  - service: notify.wesley_telegram
    data:
      message: Home Assistant is shutting down... Bye!
  mode: single
- id: '1649250204764'
  alias: System start notification
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: notify.wesley_telegram
    data:
      message: "Home Assistant has started up again \U0001F389"
  mode: single
- id: '1649250405677'
  alias: Update Gas Stations
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '30'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: dgp/gas_stations
      payload_template: '{"fuel_type":"euro95","radius":5,"latitude":{{ state_attr("person.wesley",
        "latitude") }},"longitude":{{ state_attr("person.wesley", "longitude") }},
        "to_publish":5}'
  mode: single
- id: '1649255352767'
  alias: Home Assistant update notification
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.home_assistant_versions_update_available
    to: Update Available
  condition: []
  action:
  - service: notify.wesley_telegram
    data:
      message: Home Assistant update is available
  mode: single
- id: '1651682926928'
  alias: Bedroom Dimmer Switch
  description: ''
  use_blueprint:
    path: hugalafutro/Z2M_Hue_Dimmer_Switch.yaml
    input:
      dimmer_action: sensor.bedroom_dimmer_switch_action
      action_on_press:
      - service: light.turn_on
        data: {}
        target:
          device_id: 17249d23849dd37faf257b3fe1d78ca2
      action_off_press:
      - service: light.turn_off
        data: {}
        target:
          device_id: 17249d23849dd37faf257b3fe1d78ca2
      action_off_hold:
      - service: light.turn_off
        data: {}
        target:
          area_id:
          - upstairs
      action_on_hold:
      - service: light.turn_on
        data: {}
        target:
          area_id:
          - upstairs
      action_up_hold:
      - service: light.turn_on
        data:
          brightness_step_pct: 10
        target:
          area_id: upstairs
      action_down_hold:
      - service: light.turn_on
        data:
          brightness_step_pct: -10
        target:
          area_id: upstairs
      action_up_press:
      - service: light.turn_on
        data:
          brightness_step_pct: 10
        target:
          device_id: 17249d23849dd37faf257b3fe1d78ca2
      action_down_press:
      - service: light.turn_on
        data:
          brightness_step_pct: -10
        target:
          device_id: 17249d23849dd37faf257b3fe1d78ca2
- id: '1656945637447'
  alias: Home Assistant starts ➔ Update Group - Chores
  trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: call_service
    event_data:
      domain: group
      service: reload
  condition: []
  action:
  - service: group.set
    data_template:
      name: All Chores
      object_id: chores
      entities: "{% set ns = namespace(entities=[]) %}\n{% for s in states.input_button
        if s.object_id.startswith('chore_') %}\n  {% set ns.entities = ns.entities
        + [ s.entity_id ] %}\n{% endfor %}\n{{ ns.entities }}\n"
  mode: single
- id: '1657870817731'
  alias: UniFi Protect Dynamic Doorbell
  description: ''
  use_blueprint:
    path: AngellusMortis/dynamic_doorbell.yaml
    input:
      doorbell: select.uvc_g4_doorbell_doorbell_text
      temp_entity: sensor.wupws_temp
      text_template: Welcome | {ctime} | {temp}
      time_format: '%H:%M'
- id: '1657871870764'
  alias: UniFi Protect Doorbell Notifications
  description: ''
  use_blueprint:
    path: AngellusMortis/push_notification_doorbell_event.yaml
    input:
      doorbell: binary_sensor.doorbell_uvc_g4_doorbell
      notify_target_app: wesley_iphone
      time_format: '%H:%M'
      send_mobile: true
      send_telegram: true
      notify_telegram: wesley_telegram
      base_image_url: https://weaselweb.nl
      lovelace_view: https://weaselweb.nl/lovelace
- id: '1657872083215'
  alias: UniFi Protect Motion Notifications
  description: ''
  use_blueprint:
    path: AngellusMortis/push_notification_motion_event.yaml
    input:
      motion_entity: binary_sensor.motion_uvc_g3_pro_front
      send_mobile: true
      send_telegram: true
      time_format: '%H:%M'
      notify_telegram: wesley_telegram
      base_image_url: https://weaselweb.nl
      lovelace_view: https://weaselweb.nl/lovelace
      presence_filter: person.wesley
- id: '1657874083533'
  alias: Hue Dimmer switch controller Study
  description: ''
  use_blueprint:
    path: EPMatt/philips_324131092621.yaml
    input:
      integration: Zigbee2MQTT
      helper_last_controller_event: input_text.last_controller_event_hue_dimmer_switch_study
      controller_entity: sensor.study_dimmer_switch_action
      action_button_on_short:
      - type: turn_on
        device_id: 33fe15ce0a53ea639ef8ca056bd93403
        entity_id: light.study_light
        domain: light
        brightness_pct: 80
        flash: short
      action_button_off_short:
      - type: turn_off
        device_id: 33fe15ce0a53ea639ef8ca056bd93403
        entity_id: light.study_light
        domain: light
- id: '1657874738642'
  alias: Hue Dimmer switch controller Bedroom
  description: ''
  use_blueprint:
    path: EPMatt/philips_324131092621.yaml
    input:
      integration: Zigbee2MQTT
      controller_entity: sensor.bedroom_dimmer_switch_action
      helper_last_controller_event: input_text.last_controller_event_hue_dimmer_switch_bedroom
      action_button_on_short:
      - type: turn_on
        device_id: 17249d23849dd37faf257b3fe1d78ca2
        entity_id: light.bedroom_light
        domain: light
      action_button_off_short:
      - type: turn_off
        device_id: 17249d23849dd37faf257b3fe1d78ca2
        entity_id: light.bedroom_light
        domain: light
      action_button_up_short:
      - device_id: 17249d23849dd37faf257b3fe1d78ca2
        domain: light
        entity_id: light.bedroom_light
        type: brightness_increase
      action_button_down_short:
      - device_id: 17249d23849dd37faf257b3fe1d78ca2
        domain: light
        entity_id: light.bedroom_light
        type: brightness_decrease
      action_button_off_long:
      - service: light.turn_off
        data:
          transition: 1
        target:
          area_id: upstairs
- id: '1657875007373'
  alias: Hue Dimmer switch controller Downstairs
  description: ''
  use_blueprint:
    path: EPMatt/philips_324131092621.yaml
    input:
      integration: Zigbee2MQTT
      controller_entity: sensor.living_room_dimmer_switch_action
      helper_last_controller_event: input_text.last_controller_event_hue_dimmer_switch_downstairs
      action_button_on_short:
      - service: light.turn_on
        data:
          transition: 1
        target:
          area_id: downstairs
      action_button_off_short:
      - service: light.turn_off
        data:
          transition: 1
        target:
          area_id: downstairs
- id: '1658263288463'
  alias: Windows Open Warning
  description: Sends notification to open windows. Triggered the first time each day
    that the outside temperature is more than 0.5 degrees below indoor temperature.
  trigger:
  - platform: numeric_state
    entity_id: sensor.temperature_indoor_outdoor_difference
    for:
      hours: 0
      minutes: 10
      seconds: 0
    below: '-0.5'
  condition:
  - condition: state
    entity_id: input_boolean.evening_temperature_warning_fired
    state: 'off'
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.outside_temperature
      state: unavailable
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.evening_temperature_warning_fired
    data: {}
  - service: notify.wesley_telegram
    data:
      message: It is now 0.5 degrees cooler outside than inside. Consider opening
        the windows.
      title: Cold outside!
  - service: notify.wesley_telegram
    data: {}
  mode: single
- id: '1658263443149'
  alias: Reset Morning Temperature Warning
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.morning_temperature_warning_fired
  mode: single
- id: '1658263470685'
  alias: Reset Evening Temperature Warning
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.evening_temperature_warning_fired
  mode: single
