- id: '1607949947296'
  alias: Send a camera snapshot when motion is detected
  description: ''
  use_blueprint:
    path: vorion/send-camera-snapshot-notification-on-motion.yaml
    input:
      delay: 0
      motion_sensor: binary_sensor.motion_uvc_g3_pro_front
      camera: camera.uvc_g3_pro_front
      notify_device: 62618f2f67784a4585fdff061cfb9905
      is_ios: true
- id: '1612867325017'
  alias: Home Assistant update notification
  description: ''
  use_blueprint:
    path: Klumper/update_notification.yaml
    input:
      notification_message: Home Assistant {{ newest_version }} is available
      delay: '0'
      notify_device: 62618f2f67784a4585fdff061cfb9905
      updater: binary_sensor.updater
- id: '1612867372715'
  alias: Zone Notification (FF Work Nijmegen)
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.fenne
      zone_entity: zone.work_nijmegen
      notify_device: 62618f2f67784a4585fdff061cfb9905
- id: '1612867409866'
  alias: Zone Notification (FF Work Vught)
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.fenne
      zone_entity: zone.work_vught
      notify_device: 62618f2f67784a4585fdff061cfb9905
- id: '1612980102342'
  alias: Update OpenUV 5 minutes before sunrise and after sunset
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: -00:05:00
  - platform: sun
    event: sunset
    offset: 00:05:00
  condition: []
  action:
  - service: openuv.update_uv_index_data
    data: {}
  mode: single
- id: '1612980243699'
  alias: Update OpenUV every 30 minutes during daytime
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '30'
  condition:
  - condition: and
    conditions:
    - condition: sun
      before: sunset
      after: sunrise
  action:
  - service: openuv.update_uv_index_data
    data: {}
  mode: single
- id: '1612980343472'
  alias: Update OpenUV protection window daily
  description: ''
  trigger:
  - platform: time
    at: 02:12:00
  condition: []
  action:
  - service: openuv.update_protection_data
    data: {}
  mode: single
