# Core Configuration
homeassistant: 

  # Core config
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  external_url: !secret ext_url
  internal_url: !secret int_url

  # Load packages
  packages: !include_dir_named integrations

# default_config:
default_config:

# Managed via UI
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

