---
#Core Configuration
homeassistant: !include includes/homeassistant.yaml
default_config:
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

# Include
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml

# Others
sensor: !include includes/sensors.yaml
unifiprotect: !include includes/unifiprotect.yaml
camera: !include includes/cameras.yaml
binary_sensor: !include includes/binary_sensors.yaml
badnest: !include includes/badnest.yaml
climate: !include includes/climate.yaml
spotify: !include includes/spotify.yaml

#=== Database Purging
recorder:
  purge_keep_days: 30
