
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# Include
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml

# Themes
frontend:
  themes: !include_dir_merge_named themes

# Sensors
sensor:
  - platform: afvalwijzer
    provider: afvalstoffendienstkalender
    zipcode: !secret house_zipcode
    housenumber: !secret house_number
    count_today: true

# Unifi
unifiprotect:
  host: !secret unifi_host
  username: !secret unifi_username
  password: !secret unifi_password
  port: !secret unifi_port

# Camera
camera:
  - platform: unifiprotect

#Binary sensor
binary_sensor:
  - platform: unifiprotect
