---
# Yaml Dashboard for Home Assistant

button_card_templates: !include_dir_merge_named templates/button-card/
apexcharts_card_templates: !include templates/apexcharts-card.yaml

title: Dashboard
views:
  - !include views/summary.yaml
  - !include views/lights.yaml
  - !include views/environment.yaml
  - !include views/energy.yaml
