description: Vacuum started cleaning
alias: vacuum_started_cleaning
trigger:
  platform: state
  entity_id: vacuum.xiaomi_vacuum_cleaner
  from: docked
  to: cleaning
action:
  service: notify.wesley_telegram
  data:
    message: "Robot vacuum started to clean!"






