description: Vacuum stopped cleaning
alias: vacuum_stopped_cleaning
trigger:
  platform: state
  entity_id: vacuum.xiaomi_vacuum_cleaner
  from: returning
  to: docked
action:
  - service: notify.wesley_telegram
    data_template:
      message: "Robot vacuum cleanup successful after {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'cleaning_time') }} minutes."
  - service: input_boolean.turn_on
    entity_id: input_boolean.vacuum_cleaned_today