---
description: Vacuum reset cleaned today
id: 06c6be4a-2265-44a4-8321-448000f177d2
alias: vacuum_reset_cleaned_today
trigger:
  platform: time
  at: "00:00:00"
action:
  service: input_boolean.turn_off
  entity_id: input_boolean.vacuum_cleaned_today