---
description: Vacation mode auto turn on
id: a27acee8-69f7-49df-b20b-f70b2632f3e5
alias: vacation_mode_auto_turn_on
initial_state: "on"
trigger:
  platform: state
  entity_id: group.persons
  from: home
  to: not_home
  for: "24:00:00"
condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: "off"
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.vacation_mode
  - service: notify.wesley_telegram
    data:
      message: "No one at home for 24 hours, switching on vacation mode."