---
description: Vacation mode auto turn off
id: a27acee8-69f7-49df-b20b-f70b2632f3e5
alias: vacation_mode_auto_turn_off
trigger:
  platform: state
  entity_id: group.persons
  from: not_home
  to: home
condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: "on"
  - condition: state
    entity_id: input_boolean.guest_mode
    state: "off"
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.vacation_mode
  - service: notify.wesley_telegram
    data:
      message: "Welcome back! Switching off the vacation mode."