---
description: Send notification on high CPU usage
id: fbe989ae-ccc1-4944-8b08-1e30c2ebdf25
alias: high_cpu_usage
trigger:
  - platform: numeric_state
    entity_id: sensor.processor_use
    above: 70
    for:
      hours: 2
action:
  - service: notify.wesley_telegram
    data:
      message: "CPU usage has been above 70% for 2 hours"
