---
description: Send notification on Home Assistant stop
alias: system_shutdown_notification
id: 61953d0-50cc-4f0b-81ff-3f305223ce38
trigger:
  - platform: homeassistant
    event: shutdown
action:
  - service: notify.wesley_telegram
    data:
      message: Home Assistant is shutting down... Bye!