---
description: Send notification on Home Assistant start
alias: system_start_notification
id: 104463f6-7524-48d9-bbe5-2bb09017e946
trigger:
  - platform: homeassistant
    event: start
action:
  - service: notify.wesley_telegram
    data:
      message: Home Assistant is starting up again 🎉