---
description: Send notification on Home Assistant start
id: 4664df28-525d-445d-8b7a-381aa0e458a1
alias: system_start_notification
trigger:
  - platform: homeassistant
    event: start
action:
  - service: notify.wesley_telegram
    data:
      message: Home Assistant is starting up again 🎉
