blueprint:
  name: Zigbee2Mqtt Hue Dimmer Switch control
  description: ''
  domain: automation
  input:
    dimmer_action:
      name: Dimmer Switch Action sensor
      description: Select your "sensor.dimmer_action" entity that will control this
        automation.
      selector:
        entity:
          domain: sensor
          integration: mqtt
          multiple: false
    action_on_press:
      name: on-press
      description: select action to run when you press I
      selector:
        action: {}
    action_off_press:
      name: off-press
      description: select action to run when you press O
      selector:
        action: {}
    action_up_press:
      name: up-press
      description: select action to run when you press UP
      selector:
        action: {}
    action_down_press:
      name: down-press
      description: select action to run when you press DOWN
      selector:
        action: {}
    action_on_hold:
      name: on-hold
      description: select action to run when you hold I
      selector:
        action: {}
    action_off_hold:
      name: off-hold
      description: select action to run when you hold O
      selector:
        action: {}
    action_up_hold:
      name: up-hold
      description: select action to run when you hold UP
      selector:
        action: {}
    action_down_hold:
      name: down-hold
      description: select action to run when you hold DOWN
      selector:
        action: {}
  source_url: https://gist.github.com/hugalafutro/c34ec70b688c9065ed0054b33d3f32a6
trigger:
- platform: state
  entity_id: !input 'dimmer_action'
  attribute: action
  to: on-press
- platform: state
  entity_id: !input 'dimmer_action'
  attribute: action
  to: off-press
- platform: state
  entity_id: !input 'dimmer_action'
  attribute: action
  to: up-press
- platform: state
  entity_id: !input 'dimmer_action'
  attribute: action
  to: down-press
- platform: state
  entity_id: !input 'dimmer_action'
  to: up-hold
  attribute: action
- platform: state
  entity_id: !input 'dimmer_action'
  to: down-hold
  attribute: action
- platform: state
  entity_id: !input 'dimmer_action'
  to: on-hold
  attribute: action
- platform: state
  entity_id: !input 'dimmer_action'
  attribute: action
  to: off-hold
action:
- choose:
  - conditions:
    - condition: state
      entity_id: !input 'dimmer_action'
      state: on-press
      attribute: action
    sequence: !input 'action_on_press'
  - conditions:
    - condition: state
      entity_id: !input 'dimmer_action'
      state: off-press
      attribute: action
    sequence: !input 'action_off_press'
  - conditions:
    - condition: state
      entity_id: !input 'dimmer_action'
      state: up-press
      attribute: action
    sequence: !input 'action_up_press'
  - conditions:
    - condition: state
      entity_id: !input 'dimmer_action'
      state: down-press
      attribute: action
    sequence: !input 'action_down_press'
  - conditions:
    - condition: state
      entity_id: !input 'dimmer_action'
      state: on-hold
      attribute: action
    sequence: !input 'action_on_hold'
  - conditions:
    - condition: state
      entity_id: !input 'dimmer_action'
      state: off-hold
      attribute: action
    sequence: !input 'action_off_hold'
  - conditions:
    - condition: state
      entity_id: !input 'dimmer_action'
      state: up-hold
      attribute: action
    sequence: !input 'action_up_hold'
  - conditions:
    - condition: state
      entity_id: !input 'dimmer_action'
      state: down-hold
      attribute: action
    sequence: !input 'action_down_hold'
  default: []
