---
description: Automatically turn on lights downstairs between 0800 and 2300
id: 86dcb4d5-d8fb-4209-b5e0-ef6bb60d9084
alias: turn_lights_on_downstairs
trigger:
  platform: state
  entity_id: binary_sensor.activity_in_living_room
  to: 'on'
condition:
  condition: and
  conditions:
  - condition: numeric_state
    entity_id: sensor.living_room_sensor_light_level
    below: 50
  - condition: state
    entity_id: light.downstairs
    state: 'off'
  - condition: time
    after: '08:00:00'
    before: '23:00:00'
action:
  - service: light.turn_on
    data:
      entity_id: light.downstairs
      brightness_pct: 60
  - service: notify.wesley_telegram
    data:
      message: Lights turned on downstairs
