---
description: Automatically turn off lights downstairs
id: 234e3ce7-a618-4ef9-9408-c283c52d7413
alias: turn_lights_off_downstairs
trigger:
  platform: state
  entity_id: binary_sensor.activity_in_living_room
  to: 'off'
  for:
    minutes: 60
action:
  - service: light.turn_off
    entity_id: light.downstairs
  - service: notify.wesley_telegram
    data:
      message: Lights turned off downstairs