---
description: Automatically turn off lights downstairs
id: 234e3ce7-a618-4ef9-9408-c283c52d7413
alias: turn_lights_off_downstairs
trigger:
  - platform: state
    entity_id: sun.sun
condition:
  - condition: state
    entity_id: light.downstairs
    state: 'on'
  - condition: numeric_state
    entity_id: sun.sun
    value_template: >-
      {{ state_attr('sun.sun', 'elevation') }}
    above: 1.0
action:
  - service: light.turn_off
    data:
      entity_id:
        - light.downstairs
      transition: 5