---
description: Automatically turn on night lights downstairs between 2300 and 800
id: 5a342968-89f9-4f10-a7ed-ac7d52473123
alias: turn_night_lights_on_downstairs
trigger:
  platform: state
  entity_id: binary_sensor.living_room_sensor_motion
  to: 'on'
condition:
  condition: and
  conditions:
  - condition: numeric_state
    entity_id: sensor.living_room_sensor_light_level
    below: 50
  - condition: state
    entity_id: light.downstairs
    state: 'off'
  - condition: time
    after: '23:00:00'
    before: '08:00:00'
action:
  - service: light.turn_on
    data:
      entity_id: light.living_room
      transition: 2
      brightness_pct: 10
  - service: notify.wesley_telegram
    data:
      message: Lights turned on downstairs